import nodemailer from 'nodemailer';
import { prisma } from '../../config/db';
import { WebSocketService } from '../websocket';

export interface NotificationPayload {
  userId: string;
  title: string;
  message: string;
  severity: 'WARNING' | 'CRITICAL';
  vitals?: {
    heartRate: number;
    temperature: number;
    oxygenLevel: number;
  };
}

class BrowserNotificationProvider {
  async send(payload: NotificationPayload): Promise<boolean> {
    try {
      // Emit via Socket.IO room for real-time browser notifications
      WebSocketService.emitToUser(payload.userId, 'notification', {
        title: payload.title,
        message: payload.message,
        severity: payload.severity,
        vitals: payload.vitals,
        createdAt: new Date(),
      });
      return true;
    } catch (err) {
      console.error('Failed to dispatch Browser notification:', err);
      return false;
    }
  }
}

class EmailProvider {
  private transporter: nodemailer.Transporter | null = null;

  constructor() {
    // Only initialize transporter if SMTP configurations are present
    if (process.env.SMTP_HOST && process.env.SMTP_USER) {
      this.transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST,
        port: parseInt(process.env.SMTP_PORT || '587'),
        secure: process.env.SMTP_PORT === '465', // true for 465, false for other ports
        auth: {
          user: process.env.SMTP_USER,
          pass: process.env.SMTP_PASS,
        },
      });
    }
  }

  async send(payload: NotificationPayload): Promise<boolean> {
    try {
      const user = await prisma.user.findUnique({
        where: { id: payload.userId },
        include: { profile: true },
      });

      if (!user || !user.email) {
        console.warn(`Skipping email dispatch: User ${payload.userId} email address not found.`);
        return false;
      }

      if (!this.transporter) {
        console.log(`[SMTP MOCK] Email notification to: ${user.email}`);
        console.log(`Subject: ${payload.title}`);
        console.log(`Message: ${payload.message}`);
        return true;
      }

      const mailOptions = {
        from: process.env.SMTP_FROM || '"PulseCare AI" <alerts@pulsecare.ai>',
        to: user.email,
        subject: `[PulseCare Alert] - ${payload.title}`,
        html: `
          <div style="font-family: Arial, sans-serif; padding: 20px; color: #333; max-width: 600px; border: 1px solid #ddd; border-radius: 8px;">
            <div style="background-color: ${payload.severity === 'CRITICAL' ? '#ef4444' : '#f59e0b'}; color: white; padding: 12px; border-radius: 6px; font-weight: bold; font-size: 18px;">
              PulseCare Health Monitor - ${payload.severity} Alert
            </div>
            <p style="font-size: 16px; margin-top: 15px;">Hello <strong>${user.profile?.name || 'User'}</strong>,</p>
            <p style="font-size: 15px; line-height: 1.5;">${payload.message}</p>
            ${
              payload.vitals
                ? `
              <div style="background-color: #f3f4f6; padding: 15px; border-radius: 6px; margin: 15px 0;">
                <h3 style="margin-top: 0; font-size: 14px; color: #555;">Recorded Telemetry:</h3>
                <ul style="margin-bottom: 0; padding-left: 20px;">
                  <li>Heart Rate: <strong>${payload.vitals.heartRate} BPM</strong></li>
                  <li>Body Temperature: <strong>${payload.vitals.temperature}°C</strong></li>
                  <li>Blood Oxygen: <strong>${payload.vitals.oxygenLevel}%</strong></li>
                </ul>
              </div>
            `
                : ''
            }
            <p style="font-size: 12px; color: #777; border-top: 1px solid #eee; padding-top: 15px; margin-top: 20px;">
              This is an automated alert generated by your wearable device stream connected to PulseCare AI.
            </p>
          </div>
        `,
      };

      await this.transporter.sendMail(mailOptions);
      console.log(`Email notification successfully sent to ${user.email}`);
      return true;
    } catch (err) {
      console.error('Failed to send email alert:', err);
      return false;
    }
  }
}

class SMSProvider {
  async send(payload: NotificationPayload): Promise<boolean> {
    try {
      const user = await prisma.user.findUnique({
        where: { id: payload.userId },
        include: { profile: true },
      });

      if (!user || !user.profile) {
        return false;
      }

      const emergencyName = user.profile.emergencyContactName;
      const emergencyPhone = user.profile.emergencyContactPhone;
      const patientName = user.profile.name;

      if (!emergencyPhone) {
        console.warn(`No emergency contact configured for user ${payload.userId}. SMS not sent.`);
        return false;
      }

      // Check if Twilio is enabled in configuration
      if (
        process.env.ENABLE_TWILIO_SMS === 'true' &&
        process.env.TWILIO_ACCOUNT_SID &&
        process.env.TWILIO_AUTH_TOKEN &&
        process.env.TWILIO_PHONE_NUMBER
      ) {
        console.log(`[Twilio SMS Integration Active] Attempting to dispatch emergency SMS to ${emergencyPhone}...`);
        
        // Dynamic load of Twilio or raw API execution to send SMS.
        // We will perform a raw HTTPS call to Twilio REST API to avoid forcing dependency issues
        const accountSid = process.env.TWILIO_ACCOUNT_SID;
        const authToken = process.env.TWILIO_AUTH_TOKEN;
        const fromNum = process.env.TWILIO_PHONE_NUMBER;
        const smsMessage = `[PulseCare CRITICAL] Patient ${patientName} has triggered a ${payload.severity} alert: ${payload.message}. Contact: ${user.profile.phone}`;

        // Basic Base64 encoding for basic HTTP auth
        const authString = Buffer.from(`${accountSid}:${authToken}`).toString('base64');
        const url = `https://api.twilio.com/2010-04-01/Accounts/${accountSid}/Messages.json`;
        
        const params = new URLSearchParams();
        params.append('To', emergencyPhone);
        params.append('From', fromNum);
        params.append('Body', smsMessage);

        const response = await fetch(url, {
          method: 'POST',
          headers: {
            'Authorization': `Basic ${authString}`,
            'Content-Type': 'application/x-www-form-urlencoded'
          },
          body: params
        });

        if (response.ok) {
          console.log(`Twilio SMS successfully sent to ${emergencyPhone}`);
          return true;
        } else {
          const errText = await response.text();
          console.error(`Twilio API call failed: ${response.status} - ${errText}`);
          return false;
        }
      } else {
        // SMS Fallback Log (Twilio-ready)
        console.log('\n--- [SMS MOCK ALERTS] ---');
        console.log(`To: ${emergencyPhone} (${emergencyName})`);
        console.log(`Body: [PulseCare CRITICAL] Emergency contact notified: Patient ${patientName} has triggered a ${payload.severity} alert. Message: "${payload.message}"`);
        console.log('-------------------------\n');
        return true;
      }
    } catch (err) {
      console.error('Failed to dispatch SMS notification:', err);
      return false;
    }
  }
}

export class NotificationService {
  private static browserProvider = new BrowserNotificationProvider();
  private static emailProvider = new EmailProvider();
  private static smsProvider = new SMSProvider();

  public static async sendAlert(payload: NotificationPayload): Promise<void> {
    console.log(`[NotificationService] Processing alert for User ${payload.userId}. Severity: ${payload.severity}`);
    
    // Dispatch in parallel
    await Promise.all([
      this.browserProvider.send(payload),
      this.emailProvider.send(payload),
      this.smsProvider.send(payload),
    ]);
  }
}
